FROM        FROM golang
RUN         go get github.com/sashajeltuhin/ket/provision/exec/provision-web
RUN 	    go install github.com/sashajeltuhin/KET/provision/exec/provision-web
EXPOSE	    8013
ENTRYPOINT  /go/bin/provision-web